# Generated by Django 4.1.13 on 2025-02-13 22:14

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('derma', '0004_lesion_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('imageUrl', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('ingredients', djongo.models.fields.JSONField(blank=True, default=list, null=True, verbose_name=models.CharField(max_length=256))),
            ],
        ),
        migrations.DeleteModel(
            name='Lesion',
        ),
    ]
