# Generated by Django 4.1.13 on 2025-02-14 04:31

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('derma', '0005_recipes_delete_lesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='steps',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True, verbose_name=models.CharField(max_length=256)),
        ),
    ]
