# Generated by Django 4.1.13 on 2025-04-02 21:24

import derma.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('derma', '0006_recipes_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcuatorianRecipes',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('imageUrl', models.CharField(max_length=256)),
                ('duration', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('portions', models.CharField(max_length=256)),
                ('ingredients', djongo.models.fields.ArrayField(model_container=derma.models.Ingredient)),
                ('steps', djongo.models.fields.JSONField(blank=True, default=list, null=True, verbose_name=models.CharField(max_length=256))),
                ('nutritionInfo', djongo.models.fields.EmbeddedField(model_container=derma.models.NutritionInfo)),
            ],
        ),
    ]
